# Generated by Django 4.0 on 2022-02-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roolno',
            new_name='rollno',
        ),
    ]
